### ISSUE TITLE
How do we get the source code for https://api.bhadoo.tk

### ISSUE THREAD

**Issue by bnichs5** [ParveenBhadooOfficial/Cloudflare-Proxy-Server#1]
It appears that we need the source code for https://api.bhadoo.tk in order for this to fully work. Otherwise we are reliant on your website in order to use this. Could you please provide the code for the site?

Thank you!

**Comment by bnichs5** [comment]
Sorry. I am wrong, it still works. The website i am trying to access seems to have blocked my workers url, but your still works for some reason.

**Comment by ramdibaaz** [comment]
> It appears that we need the source code for https://api.bhadoo.tk in order for this to fully work. Otherwise we are reliant on your website in order to use this. Could you please provide the code for the site?
> 
> Thank you!

yes i truly agree with it

**Comment by ParveenBhadooOfficial** [comment]
https://github.com/jscdn/proxyapi
